[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    # Cross-Origin-Resource-Policy = "cross-origin"
    # Access-Control-Allow-Origin = "*"
    # Cache-Control = "no-cache, no-store, must-revalidate"
    # Pragma = "no-cache"
    # Expires = "0"
